### ISSUE TITLE
BluetoothMessageProtocol didn't compile under Xcode 11.4 beta.

### ISSUE THREAD

**Issue by Harry090920** [FitnessKit/BluetoothMessageProtocol#1]
Pod BluetoothMessageProtocol cannot be compiled under Xcode 11.4 beta.  Please help.

<img width="1680" alt="Screen Shot 2020-02-24 at 2 07 43 PM" src="https://user-images.githubusercontent.com/61431498/75184116-db170180-5711-11ea-86b2-9d9f948e052d.png">

**Comment by khoogheem** [comment]
I will start looking at the Beta Stuff this weekend... It might also include a few other enhancements that I have been looking at.

**Comment by khoogheem** [comment]
There is a swift52 branch with fixes for Swift 5.2. 11.4 Xcode..

Please note, that Characteristics, ManufacturerData and Service Data are no longer subclass able.. However to keep things pretty much the same right now I feel this is a fare tradeoff.

**Comment by Harry090920** [comment]
Can I use pod install to get this swift52 branch?

**Comment by khoogheem** [comment]
sure.. you just need to use the format:
`pod 'BluetoothMessageProtocol', :git => 'https://github.com/FitnessKit/BluetoothMessageProtocol.git', :branch => 'swift52'`

**Comment by khoogheem** [comment]
I still have to make sure all the Characteristics conform to Hashable.. Right now I think that is the only thing that might still trip you up if you are doing any comparisons on them.

**Comment by Harry090920** [comment]
what can cause this message?
-bash: https://github.com/FitnessKit/BluetoothMessageProtocol.git,: No such file or directory

**Comment by khoogheem** [comment]
you replaced what you had with the new line which looks for a specific branch?

**Comment by Harry090920** [comment]
Yes, installed successfully. New issue in the class 'ManufacturerDataAppleHomeKit' -> 'SHA512' is only available in application extensions for watchOS 6.0 or newer. It's in the line 135. My deployment target in WatchKit/WatchKit Extension is 6.0.

**Comment by khoogheem** [comment]
All other deployment targets are setup correctly?  or I should ask what are they set to..

**Comment by Harry090920** [comment]
updated iOS target to 13.4, no changes.

**Comment by khoogheem** [comment]
hmm.. ok.. I probably need to put back @available and add the extension in there.. and fall back to the old crypto system.

odd though it is acting like the target is not set correctly to what you say you have it set

CryptoSwift basically has this check:
(iOS 13.0, OSX 10.15, watchOS 6.0, tvOS 13.0, *)

which if you have it set to 6.0 it should be working

**Comment by Harry090920** [comment]
yep, strange.

**Comment by Harry090920** [comment]
should work with watchOS 6.

**Comment by Harry090920** [comment]
any updates with the @available and adding the extension?

**Comment by khoogheem** [comment]
if you can check it out by modifying the local source that would be great. I have not had the time to do this and won't until the weekend.

**Comment by khoogheem** [comment]
can you post your pod file... I will have some time this weekend to look at it..

**Comment by Harry090920** [comment]
target 'WatchKit Extension' do
  platform :watchos, '6.0'
  use_frameworks!

  pod 'BluetoothMessageProtocol', :git => 'https://github.com/FitnessKit/BluetoothMessageProtocol.git', :branch => 'swift52'
  pod 'Zip'

end

**Comment by khoogheem** [comment]
ok.. I am now finally seeing it and yes.. the available looks like the right fix.. so I will be pushing up some changes today..

**Comment by khoogheem** [comment]
ok.. all is updated

**Comment by khoogheem** [comment]
I am going to close this one

**Comment by Harry090920** [comment]
thanks, no issues were found so far.
