### ISSUE TITLE
Xcode 12 warning: Unnecessary check for 'iOS'

### ISSUE THREAD

**Issue by tealshift** [FitnessKit/BluetoothMessageProtocol#4]
Warning appears when building for iOS 14:
**BluetoothMessageProtocol/ManufacturerData/ManufacturerDataAppleHomeKit.swift:144:16: Unnecessary check for 'iOS'; enclosing scope ensures guard will always be true**

<img width="474" alt="Screen Shot 2020-09-08 at 12 45 13 PM" src="https://user-images.githubusercontent.com/7879237/92520876-276af000-f1d1-11ea-9268-6e5cf575435d.png">

**Comment by khoogheem** [comment]
yah... In older versions this "unnecessary" check is needed
and if I recall without it either via SPM or Pods (can't recall which) there were issues.

So right now given it is warning I am not going to address it for now..
